name: Oceanist Insight Engine

on:
  schedule:
    - cron: '30 1 * * 1,3,5,0'
  workflow_dispatch:
    inputs:
      script_to_run:
        description: 'Which script to run manually?'
        required: true
        type: choice
        options:
        - news_curator
        - fishing_analyzer
        - oilgas_analyzer

jobs:
  run-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - uses: actions/checkout@v4
        with:
          # This token is required for the pull/push to work
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - run: pip install -r requirements.txt

      # ... (The three script-running steps remain the same) ...
      - name: Run NEWS script
        if: ...
      - name: Run FISHING script
        if: ...
      - name: Run OIL & GAS script
        if: ...

      - name: Pull latest changes to avoid conflicts
        run: git pull

      - name: Commit changes to GitHub
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "feat(data): update insight and log files"
          # This pattern will correctly save any changed log file
          file_pattern: "*.log *.json"

      - name: ⬆️ Upload insight file to Server
        run: |
          # ... (The FTP upload script remains the same) ...
