name: News Curator Engine

on:
  schedule:
    # Runs at 01:30 UTC on Wednesday and Sunday
    - cron: '30 1 * * 3,0'
  workflow_dispatch: # This allows us to run it manually from the Actions tab

jobs:
  run-curator:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Checkout repository
        uses: actions/checkout@v4

      - name: 2. Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: 3. Install dependencies
        run: pip install -r requirements.txt

      - name: 4. Run the news curator script
        env:
          # Make the API key available to the script
          AI_API_KEY: ${{ secrets.AI_API_KEY }}
        run: python run_news_curator.py

      - name: 5. Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "feat: update news log and insight data"
          file_pattern: "*.log *.json"
