name: Oceanist Insight Engine

on:
  schedule:
    - cron: '30 1 * * 1,3,5,0'
  workflow_dispatch:
    inputs:
      script_to_run:
        description: 'Which script to run manually?'
        required: true
        type: choice
        options:
        - news_curator
        - fishing_analyzer
        - oilgas_analyzer

jobs:
  run-analysis:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - run: pip install -r requirements.txt

      - name: Run NEWS script
        if: (github.event_name == 'schedule' && (github.event.schedule == '30 1 * * 3' || github.event.schedule == '30 1 * * 0')) || (github.event_name == 'workflow_dispatch' && github.event.inputs.script_to_run == 'news_curator')
        env:
          AI_API_KEY: ${{ secrets.AI_API_KEY }}
          GITHUB_EVENT_NAME: ${{ github.event_name }}
        run: python run_news_curator.py

      - name: Run FISHING script
        if: (github.event_name == 'schedule' && github.event.schedule == '30 1 * * 1') || (github.event_name == 'workflow_dispatch' && github.event.inputs.script_to_run == 'fishing_analyzer')
        env:
          AI_API_KEY: ${{ secrets.AI_API_KEY }}
          GITHUB_EVENT_NAME: ${{ github.event_name }}
        run: python run_fishing_analyzer.py

      - name: Run OIL & GAS script
        if: (github.event_name == 'schedule' && github.event.schedule == '30 1 * * 5') || (github.event_name == 'workflow_dispatch' && github.event.inputs.script_to_run == 'oilgas_analyzer')
        env:
          AI_API_KEY: ${{ secrets.AI_API_KEY }}
          GITHUB_EVENT_NAME: ${{ github.event_name }}
        run: python run_oilgas_analyzer.py

      - name: Commit changes to GitHub
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "feat(data): update insight and log files"
          file_pattern: "*.log *.json"

      - name: ⬆️ Upload insight log to Server (No Deletions)
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps
          port: 21
          # This uploads the single log file into the server directory
          local-dir: ./
          server-dir: /public_html/map-data/
          # This is the correct way to upload ONLY the log file and touch NOTHING else
          exclude: "**"
          include: "insights_log.json"
