name: 🎣 Fishing Analyzer

on:
  schedule:
    - cron: '30 1 * * 1' # Runs on Mon
  workflow_dispatch:

jobs:
  run-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - run: pip install -r requirements.txt
      - name: Run FISHING script
        env:
          AI_API_KEY: ${{ secrets.AI_API_KEY }}
        run: python run_fishing_analyzer.py
      - name: ⬆️ Upload fishing_insight.json
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps
          port: 21
          # Corrected indentation for exclude
          exclude: |
            **/*
            !fishing_insight.json
