name: '🛢️ Oil & Gas Analyzer'

on:
  schedule:
    - cron: '30 1 * * 5' # Runs on Fri
  workflow_dispatch:

jobs:
  run-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - run: pip install -r requirements.txt
      - name: Run OIL & GAS script
        env:
          AI_API_KEY: ${{ secrets.AI_API_KEY }}
        run: python run_oilgas_analyzer.py
      - name: ⬆️ Upload oilgas_insight.json
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps
          port: 21
          # This safe pattern uploads ONLY the target file
          exclude:
            - "**/*"
            - "!oilgas_insight.json"
